"""empty message

Revision ID: 5a3d12aba33c
Revises: cf7014b1ef94
Create Date: 2019-01-14 14:12:32.693853

"""

# revision identifiers, used by Alembic.
revision = '5a3d12aba33c'
down_revision = 'cf7014b1ef94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fcm_email_notification_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg_md5', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('msg', sa.Text(), nullable=True),
    sa.Column('msg_send_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fcm_email_notification_tables')
    # ### end Alembic commands ###
