"""empty message

Revision ID: 940ce70b144d
Revises: 5a3d12aba33c
Create Date: 2019-01-14 15:56:53.057170

"""

# revision identifiers, used by Alembic.
revision = '940ce70b144d'
down_revision = '5a3d12aba33c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fcm_email_notification_tables', sa.Column('table_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('fcm_email_notification_tables', 'table_id')

    # ### end Alembic commands ###
