"""empty message

Revision ID: cf7014b1ef94
Revises: 55e910a74826
Create Date: 2019-01-11 10:05:25.678441

"""

# revision identifiers, used by Alembic.
revision = 'cf7014b1ef94'
down_revision = '55e910a74826'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('tables', sa.Column('is_monitor', sa.Boolean(), nullable=True, server_default=sa.false()))
    op.add_column('tables', sa.Column('monitor_dttm_column', sa.Text(), nullable=True))
    op.add_column('tables', sa.Column('notify_emails', sa.Text(), nullable=True))
    op.add_column('tables', sa.Column('notify_template', sa.Text(), nullable=True))
    op.add_column('tables', sa.Column('threshold_of_day', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('tables', 'threshold_of_day')
    op.drop_column('tables', 'notify_template')
    op.drop_column('tables', 'notify_emails')
    op.drop_column('tables', 'monitor_dttm_column')
    op.drop_column('tables', 'is_monitor')
    # ### end Alembic commands ###
